services:

  cfgsync:
    container_name: cfgsync
    build:
      context: .
      dockerfile: testnet/Dockerfile
    image: logos-blockchain:latest
    volumes:
      - ./testnet:/etc/logos-blockchain
    environment:
      - ENTROPY_FILE=/etc/logos-blockchain/testnet/cfgsync/tests/test_entropy
    entrypoint: /etc/logos-blockchain/scripts/run_cfgsync_server.sh

  logos-blockchain-node:
    build:
      context: .
      dockerfile: testnet/Dockerfile
    volumes:
      - ./testnet:/etc/logos-blockchain
    deploy:
      replicas: ${DOCKER_COMPOSE_LIBP2P_REPLICAS:-1}
    depends_on:
      - cfgsync
    entrypoint: /etc/logos-blockchain/scripts/run_logos_blockchain_node.sh
