events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # Public
    server {
        listen 13000;
        server_name _;

        # CFGSYNC API (Proxy to the internal Docker service).
        location /cfgsync/ {
            proxy_pass http://cfgsync:4400/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Static content on https://$EVN_TITLE_STRING.blockchain.logos.co/web/.
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }

    # Protected
    server {
        listen 13001;
        server_name _;

        # Expose all nodes data on https://$EVN_TITLE_STRING.blockchain.logos.co/internal/node-data/.
        location /node-data/ {
            alias /node-data/;
            autoindex on;
        }
    }
}
