blend:
  common:
    num_blend_layers: 3
    timing:
      rounds_per_session: 648000
      rounds_per_interval: 30
      round_duration: '1.000000000'
      rounds_per_observation_window: 30
      rounds_per_session_transition_period: 30
      epoch_transition_period_in_slots: 2600
    minimum_network_size: 30
    protocol_name: /blend/integration-tests
    data_replication_factor: 0
  core:
    scheduler:
      cover:
        message_frequency_per_round: 1.0
        intervals_for_safety_buffer: 100
      delayer:
        maximum_release_delay_in_rounds: 3
    minimum_messages_coefficient: 1
    normalization_constant: 1.03
network:
  kademlia_protocol_name: /integration/logos-blockchain/kad/1.0.0
  identify_protocol_name: /integration/logos-blockchain/identify/1.0.0
  chain_sync_protocol_name: /integration/logos-blockchain/chainsync/1.0.0
cryptarchia:
  epoch_config:
    epoch_stake_distribution_stabilization: 3
    epoch_period_nonce_buffer: 3
    epoch_period_nonce_stabilization: 4
  security_param: 10
  sdp_config:
    service_params:
      BN:
        lock_period: 10
        inactivity_period: 20
        retention_period: 100
        timestamp: 0
        session_duration: 21600
    min_stake:
      threshold: 1
      timestamp: 0
  gossipsub_protocol: /integration/logos-blockchain/cryptarchia/proto/1.0.0
time:
  slot_duration:
    secs: 5
    nanos: 0
mempool:
  pubsub_topic: mantle_e2e_tests