events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 18080;
        server_name _;

        # CFGSYNC API (Proxy to the internal Docker service).
        location /cfgsync/ {
            proxy_pass http://cfgsync:4400/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Block Explorer
        location /explorer/ {
            proxy_pass http://explorer:8000/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Connection '';
            proxy_buffering off;
            proxy_cache off;
            chunked_transfer_encoding off;

        # Faucet mapping from outside to internal docker net.
        location /faucet/0/ {
            proxy_pass http://logos_blockchain_node_0:18090/faucet/;
        }

        location /faucet/1/ {
            proxy_pass http://logos_blockchain_node_1:18090/faucet/;
        }

        location /faucet/2/ {
            proxy_pass http://logos_blockchain_node_2:18090/faucet/;
        }

        location /faucet/3/ {
            proxy_pass http://logos_blockchain_node_3:18090/faucet/;
        }

        # Static content on https://devnet.blockchain.logos.co/node/0/.
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
